# Generated by Django 5.0.6 on 2024-07-09 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id_tipo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_prestamo', models.CharField(max_length=50)),
                ('tasa_de_interes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('RUT_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('apellido_empleado', models.CharField(max_length=50)),
                ('direccion_empleado', models.CharField(max_length=100)),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_prestamo', models.IntegerField()),
                ('monto_pagar', models.IntegerField(blank=True, null=True)),
                ('cantidad_cuotas', models.IntegerField()),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empleado')),
                ('TipoPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipoprestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('monto_cuota', models.IntegerField()),
                ('cuota_fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cuota_fecha_vencimiento', models.DateTimeField()),
                ('cuota_fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('Prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='myapp.prestamo')),
            ],
        ),
    ]
